### ISSUE TITLE
json2xml and configuration options

### ISSUE THREAD

**Issue by tla** [DHUniWien/tpen2tei#8]
For the purposes of the @DHUniWien/snsf project, json2xml needs to be able to pass both `special_chars` and `numeric_parser` to `parse.from_sc`. When that gets done, the parsing-to-XML pipeline will be a major step closer to producing valid TEI.

**Comment by oftl** [comment]
A new function called `json2xml` in `tpen2tei.json2xml` now accepts the new parameters (since it is python code this is not available from the commandline).

Usage is demonstrated in `moe-data/ci/resources/json2xml.py`. Parameters to ues in the moe-data pipeline can be set there in the function of equal name.
